//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Profileid { get; set; }
        public string Tittle { get; set; }
        public string Description { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public string Githup { get; set; }
        public string İmageUrl { get; set; }
        public string MapLocation { get; set; }
    }
}
