//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int Servicesİd { get; set; }
        public string Tittle { get; set; }
        public string Description { get; set; }
        public string İcon { get; set; }
    }
}
